import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df=pd.read_csv(r'C:\Users\carnival\.cache\kagglehub\datasets\vivek468\superstore-dataset-final\versions\1\Sample - Superstore.csv', encoding='latin1')
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])
print('Sales:\n',df.groupby('Region')['Sales'].sum().sort_values())
print('Profit:\n',df.groupby('Region')['Profit'].sum().sort_values())
print('Discounts:\n',df.groupby('Region')['Discount'].mean().sort_values())
import seaborn as sns

subprofit = df.groupby('Sub-Category')['Profit'].sum().sort_values()
print(subprofit)
plt.figure(figsize=(10,6))
subprofit.plot(kind='bar', color=np.where(subprofit < 0, 'salmon', 'skyblue'))
plt.title('Total Profit by Sub-Category')
plt.ylabel('Profit')
plt.xticks(rotation=45)
plt.show()
plt.savefig("C:/Users/carnival/Desktop/plot1.png")
correlation = df['Discount'].corr(df['Profit'])
print("correlation between profit and discount", correlation)

plt.figure(figsize=(8, 6))
sns.regplot(data=df, x='Discount', y='Profit')
plt.title('Relationship between Discount and Profit')
plt.xlabel('Discount')
plt.ylabel('Profit')
plt.grid(True)
plt.tight_layout()
plt.show()
plt.savefig("C:/Users/carnival/Desktop/plot2.png")
df['Year'] = df['Order Date'].dt.to_period('Y')
Sales_Year=df.groupby('Year')['Sales'].sum()
plt.bar(Sales_Year.index.astype(str), Sales_Year.values, color='orange')
plt.xlabel('Years')
plt.ylabel('Sales')
plt.title('Total Sales per Year')
plt.tight_layout()
plt.show()
customers = df.groupby(['Customer ID', 'Customer Name'])['Sales'].sum().sort_values(ascending=False).head()
print("Top 5 Customers:\n", customers)
segment= df['Segment'].value_counts().sort_values(ascending=False)
sns.barplot(x=segment.index, y=segment.values, palette='Blues')
plt.title("Number of Orders per Segment")
plt.ylabel("Orders")
plt.xlabel("Segment")
plt.show()
plt.savefig("C:/Users/carnival/Desktop/plot3.png")
top_products = df.groupby('Product Name')['Quantity'].sum().sort_values(ascending=False).head(10)
top_products.plot()
plt.title("Top 10 Selling Products")
plt.xlabel("Quantity Sold")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
plt.savefig("C:/Users/carnival/Desktop/plot4.png")
